### ISSUE TITLE
مشکل نا مشخص در نصب اسکریپت

### ISSUE THREAD

**Issue by rmombeni** [rezaee/raspina#1]
با سلام
و خسته نباشید خدمت شما دوست عزیز
لازمه به عرضتون برسونم که موقع نصب اسکریپت بعد از وارد کردن دیتابیس و تنظیمات خواسته شه نصب رو که می زنی میگه به دلیل خطای زیر جداول دیتابیس ساخته نشده
و همچنین هیچ خطایی در زیر قید نشده
ممنون می شم راهنمایی بفرمایید

**Comment by rezaee** [comment]
،سلام
نیازمندی های رَسپنا رو به دقت بررسی کنید
url.com/requirements.php
مطمئن بشید اکستنشن های زیر فعال هستند
extension=pdo.so
extension=php_pdo.dll
extension=php_pdo_mysql.dll
سطح دسترسی مسیر زیر را 777 بذارید
common/config
همچینین تابع زیر باید فعال و قابل اجرا باشد
exec()
موفق باشید
