### ISSUE TITLE
نصب روی لوکال هاست

### ISSUE THREAD

**Issue by varnasoft** [rezaee/raspina#3]
روی لوکال با چه برنامه ای بالا میاد ، با 
xampp 
امتحان کردم نشد و اینکه روی هاستهای اشتراکی هم پرسیدم که باید از سرور مجازی استفاده کرد

**Comment by rezaee** [comment]
،سلام
تفاوتی در استفاده از 
xampp/wamp
وجود نداره
شما چه مشکلی هنگام نصب دارید؟
در ضمن نیازی به استفاده از سرور مجازی نیست، وبلاگ من با استفاده از همین پروژه روی هاست اشتراکی نصب شده

**Comment by varnasoft** [comment]
Warning: require(db_config.php): failed to open stream: No such file or directory in /home3/varnasof/public_html/schvarna.ir/common/config/main-local.php on line 2

Warning: require(db_config.php): failed to open stream: No such file or directory in /home3/varnasof/public_html/schvarna.ir/common/config/main-local.php on line 2

Fatal error: require(): Failed opening required 'db_config.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home3/varnasof/public_html/schvarna.ir/common/config/main-local.php on line 2
---------------
همچین اروری میده

**Comment by rezaee** [comment]
سطح دسترسی فهرست زیر را 777 بذارید
common/config

**Comment by varnasoft** [comment]
به دلیل خطای زیر جداول دیتابیس ایجاد نشده اند. 

 Warning: exec() has been disabled for security reasons in /home3/varnasof/public_html/schvarna.ir/install.php on line 89

**Comment by varnasoft** [comment]
![capture](https://cloud.githubusercontent.com/assets/20749750/17275723/b6c968d4-5726-11e6-8fc9-2edb132231ff.PNG)

**Comment by rezaee** [comment]
در اینجا توضیح دادم
https://github.com/rezaee/raspina/issues/1
تابع زیر باید فعال و قابل اجرا باشد
exec()
